### ISSUE TITLE
dependencies broken

### ISSUE THREAD

**Issue by joshuaandrews63** [negativo17/avidemux#2]
Problem 1: cannot install both kvazaar-libs-2.0.0-1.fc31.x86_64 and kvazaar-libs-1.3.0-1.fc31.x86_64
  - package compat-ffmpeg-libs-1:3.4.7-1.fc31.x86_64 requires libkvazaar.so.4()(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package kvazaar-libs-1.3.0-1.fc31.x86_64
  - problem with installed package compat-ffmpeg-libs-1:3.4.7-1.fc31.x86_64
 Problem 2: cannot install both x265-libs-1:3.4-1.fc31.x86_64 and x265-libs-1:3.2.1-1.fc31.x86_64
  - package avidemux-gui-1:2.7.3-4.fc30.x86_64 requires libx265.so.179()(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package x265-libs-1:3.2.1-1.fc31.x86_64
  - problem with installed package avidemux-gui-1:2.7.3-4.fc30.x86_64
 Problem 3: cannot install both x265-libs-1:3.4-1.fc31.x86_64 and x265-libs-1:3.2.1-1.fc31.x86_64
  - package ffmpeg-libs-1:4.3-4.fc31.x86_64 requires libx265.so.192()(64bit), but none of the providers can be installed
  - package avidemux-libs-1:2.7.3-4.fc30.x86_64 requires libx265.so.179()(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package ffmpeg-libs-1:4.2.2-1.fc31.x86_64
  - problem with installed package avidemux-libs-1:2.7.3-4.fc30.x86_64
 Problem 4: cannot install both x265-libs-1:3.4-1.fc31.x86_64 and x265-libs-1:3.2.1-1.fc31.x86_64
  - package gstreamer1-plugins-bad-1:1.16.2-7.fc31.x86_64 requires libx265.so.192()(64bit), but none of the providers can be installed
  - package avidemux-libs-1:2.7.3-4.fc30.x86_64 requires libx265.so.179()(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package gstreamer1-plugins-bad-1:1.16.1-2.fc31.x86_64
  - cannot install the best update candidate for package avidemux-libs-1:2.7.3-4.fc30.x86_64

**Comment by scaronni** [comment]
It was left to bit rot for a while as I was not using it... Updated and cleaned up. Thanks for reporting.
